### ISSUE TITLE
Fade Transition

### ISSUE THREAD

**Issue by neuralyzer** [senshu/Sozi#190]
I love sozi and I use it for all my presentation.

However, sometimes I do not want to have all that movement between different slides. I then use the "immediate" transition to hop from one slide to the next one. Unluckily this does not look very smooth. So I was wondering if one could add a smooth fade transition. By fading I don't think of fading between different layers, but rather of fading from one view to the next one.

**Comment by MenschMarcus** [comment]
I would like to pick up on this again. I am a sozi user as well, I love it, but I have to admit: Fading in and out slowly is the great advantage of slide-based presentation software. And this is the only reason why I still use LO Impress sometimes, because sometimes it is just necessary to switch to a totally new topic where I do not want to
a) transition to slowly or
b) jump to immediately

While I totally accept you saying "it is difficult to implement" I can guarantee you that you will have plenty of more happy users (just like me or neuralyzer). An to my mind, software development should be user-centered ;) I would be incredibly happy about this feature!

**Comment by senshu** [comment]
@MenschMarcus This issue was opened in 2013 and relates to an old version of Sozi.

Fade in/out is possible in Sozi 15. Please read [the comment I wrote about a similar issue](https://github.com/senshu/Sozi/issues/175#issuecomment-96069225). Basically, you can achieve a similar effect as in Impress by putting the content of two adjacent frames in separate layers and playing with the Opacity property in the presentation editor.

**Comment by MenschMarcus** [comment]
ok, thank you :)
