### ISSUE TITLE
Sozi player in Ruby-Processing

### ISSUE THREAD

**Issue by poqudrof** [senshu/Sozi#299]
Hello, 

I have been playing around with Processing for some time now, and I liked a lot Prezi. However Prezi got super slow, and closed. Meanwhile Sozi got really nice and I use Inkscape a lot. 
So I told myself : "Why not make a Sozi - svg player in Processing ?", then it moved to [Ruby-Processing](https://github.com/jashkenas/ruby-processing) to enable coding in slides (yes I am a little bit crazy). 

After a few [Processing patches](https://github.com/poqudrof/processing/releases/tag/2.2.1-svg) I have the SVG loaded with images from file system or embedded. With a few easy tricks I got the videos displayed as Processing has a video player.  I handle slide transitions like in Sozi, and I translated most of the javascript to Ruby. 

Then, I figured that I could also add "simple" slide animations : elements appearing, which was missing from Sozi.  

I did a presentation with this "software",  which was quite nice, but the presentation SVG did not look good, nor was fully compatible with Sozi. 

A few months ago, I made a [ruby gem called Soby](https://rubygems.org/gems/soby/versions/0.0.2) of the code to create new presentations. It is much slower and memory-heavy than a browser because of the Processing rendering engine, but it starts to look nice. I experimented a little, and we can set our own "transition shaders"  in [Processing shaders](https://processing.org/tutorials/pshader/) to have like motion blur, or fast generative designs. 

OK, so, why the long post ? It is quite simple, Ruby-Processing is a young project in which I am quite excited, and I have that Processing will get faster and a better SVG support. 

So I would like to know if the **inkscape support will be still on ?** If not why ?  I would like to have a preview mode for my presentations, so that I can edit in inkscape and preview in real-time with Soby. 

Thanks for the great work so far, I have had much fun rewriting part of the player's code in Ruby !

Jeremy.

**Comment by senshu** [comment]
Hi, Jeremy.

Thanks for sharing your work. I didn't know about ruby-processing.

> So I would like to know if the inkscape support will be still on ?

Sozi 15 is intended to be independent from any particular SVG editor.
Inkscape is still supported but Sozi is no longer an Inkscape extension. It is a separate application that you can run in parallel with Inkscape.

> I would like to have a preview mode for my presentations, so that I can edit in inkscape and preview in real-time with Soby.

I'm not sure what "in real-time" means in this context.

In Sozi 15, the editor shows a preview of each frame, but it does not animate the transitions yet.
If I understand well, I suppose that Sozi 15 will be as good as Sozi 13 for your needs.

I see that Soby is based on the file format of Sozi 13 where presentation data are added as XML elements into the SVG document. If you plan to use Sozi 15, be aware that the file format has been changed completely:
* The original SVG document is no longer modified by the presentation editor.
* Presentation data are stored separately into a JSON file.

Please read the [release notes of Sozi 15.05](http://sozi.baierouge.fr/release-15.05.html) for more details. The source code is in the `preview` branch of this repository. Some bugs have been fixed since the official prerelease. Install the [latest nightly builds](https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0&authuser=0) to try.

**Comment by senshu** [comment]
The original report was not an issue but only a question. Feel free to reopen it if you think it has not been properly addressed.
