### ISSUE TITLE
toxic slides in presentation make all content disappear

### ISSUE THREAD

**Issue by andemil** [senshu/Sozi#303]
Hi,

I think I found a bug in Sozi 15.05.142313, which as far as I can tell was not reported before. I prepared a presentation in which certain slides seem to be toxic. Every time I try to view them (with either firefox or chrome) all content disappears from the slides. These are slides 21-28 in the file downloadable from
http://content.wuala.com/contents/andemil/public/k-center.zip
Viewing any other slide works as expected. But jumping to any of the toxic slides will make all content invisible, even when going back to some non-toxic slide. In Sozi everthing looks normal and the content is displayed. What is going on here?

Thanks,
/Andreas

**Comment by senshu** [comment]
This issue is old and I did not take the time to inspect the given files. Sorry about that.
Now the link to the files is broken.

There have been many changes in Sozi since this issue was reported, so I will advise you to try the latest development version from https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0 and reopen this issue if it is still relevant.
