### ISSUE TITLE
Installation SOZI 16 sur Ubuntu

### ISSUE THREAD

**Issue by Juju25** [senshu/Sozi#356]
I Left Windows for Ubuntu BUT I don't succeed in installing SOZI 16... What are the steps? Thanks...

**Comment by senshu** [comment]
Have you read the instructions from this page: http://sozi.baierouge.fr/pages/20-install.html ?

**Comment by Juju25** [comment]
Yes : "Unzipping the archive will create a folder with the same name. Linux and Windows users will run Sozi by launching the Sozi executable inside that folder. "  I did it but i didn't succeed. Must I follow the previous instructions (sozi 13)?

**Comment by cocofifi** [comment]
What happens if you launch the Sozi executable from the folder ? In my case, after unzip, I get the folder called `Sozi-16.02.141048-linux64`. The easiest way to launch Sozi is to use the Terminal to go into that folder and to launch Sozi by entering `./Sozi`. Should work - if it does not you will get informative error messages in the Terminal.

**Comment by senshu** [comment]
> I did it but i didn't succeed

What does "didn't succeed" mean exactly?
I can't help you if you don't give more details.

> Must I follow the previous instructions (sozi 13)

No.

**Comment by Juju25** [comment]
As I'm discovering Ubuntu, maybe the way I launch Sozi is not the good one. I restart with cocofifi advice.
When I write "didn't succeed" I mean Sozi does not run. Keep in touch.
Thanks!

**Comment by Juju25** [comment]
Ok I got it.
I'm sorry. The new SOZI is so different from the previous one (extension in inkscape). I made a real mistake. At the begining, the grey window disturbed me, I thought it did not work...

**Comment by Juju25** [comment]
Thank you very much for your help!
