### ISSUE TITLE
Sozi 16.02 more link média

### ISSUE THREAD

**Issue by lagrattecchouette** [senshu/Sozi#369]
In previous versions we had possibité on an image to create a link to a video or picture. In the 16.02 version of I do not see this possibility. Yet when downloading => Sozi-16.02.141048-win64.zip / Sozi-extras-media-16.02.141048.zip ago a well sozi EXTRA MEDIA file.
But I do not know how to operate it.

Help ...

**Comment by senshu** [comment]
Have you tried to follow these instructions?
http://sozi.baierouge.fr/pages/tutorial-media.html

**Comment by lagrattecchouette** [comment]
Sure it works well using these instructions.
But I thought you can not use INSCKAPE with the 16.02 release since that was now all settings in the latest version.
It still lacks the ability to create a link to a PDF that was in previous versions.

How to do ?

**Comment by senshu** [comment]
> But I thought you can not use INSCKAPE with the 16.02

Who said that? You are not *obliged* to use Inkscape but you are still supposed to use an SVG editor to create your base document. Inkscape is a good choice for that.

Media insertion has always been independent from the core part of Sozi. That's why it appears in the "Sozi extras" category.

> It still lacks the ability to create a link to a PDF that was in previous versions.

This feature is available natively in Inkscape. You can create links to whatever you want.
This page gives more details on that feature: http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Web-Links.html

**Comment by lagrattecchouette** [comment]
Hello,
Thank you for this valuable information.
But using the line under INSCKAPE it does not work.
Are Has there another way to write the path to the document?
Here is my link ...

xlink:href="C:\Users\SRZ\Documents\Sozi\Projets\Demarrage\ppt\Presentation1.ppsx"

**Comment by senshu** [comment]
Answered at #371. Closing this issue since it is not related to Sozi.
