### ISSUE TITLE
Embedding Sozi 16.2

### ISSUE THREAD

**Issue by batisteo** [senshu/Sozi#379]
Is it possible to embed a Sozi document?
I tried embedding the outputed HTML in `object` or `iframe`, but it looks funny.

**Comment by senshu** [comment]
"it looks funny" is not a very helpful description of your problem. What do you expect me to do?
Can you please report this issue again and fill the requested information?

**Comment by charles-plessy** [comment]
Hello, I have created a naive test page showing that Sozi presentations in SVG format are easier to embed than the HTML ones, because the HTML ones get squeezed in small boxes.

https://cdn.rawgit.com/charles-plessy/sozi-pandoc-embed-test/7775e4c5d36fb65e6b01468589c75195502bec65/Sozi-embed.html

Batisteo, is that what you meant by "looks funny" ?

([Pandoc source](https://raw.githubusercontent.com/charles-plessy/sozi-pandoc-embed-test/7775e4c5d36fb65e6b01468589c75195502bec65/Sozi-embed.md))

**Comment by senshu** [comment]
@charles-plessy Please do not add comments to a closed issue. You can ask to reopen it if you are sure it is related to your problem, but in this case, we don't know what the original poster meant. I would prefer that you opened a new issue with a detailed explanation of your problem. Thanks.
