### ISSUE TITLE
Sozi in format DEB (32bits and 64bits)

### ISSUE THREAD

**Issue by amartinr1977** [senshu/Sozi#388]
Hi Senshu!!
I am working in a free software proyect in Spain (https://github.com/Vitalinux-DGA-ProgSoftLibre) and I am created a DEB package from Sozi.17-2 for 32 and 64 bits:

http://migasfree.educa.aragon.es/repo/Lubuntu-14.04/STORES/base/vx-dga-l-sozi_1.0-2_amd64.deb
http://migasfree.educa.aragon.es/repo/Lubuntu-14.04/STORES/base/vx-dga-l-sozi_1.0-2_i386.deb

We work with Lubuntu 14.04 but these packages could be installed in others derivate Ubuntu distros.
Congratulations, Sozi's a good work!!!

**Comment by senshu** [comment]
I'm glad that you made Sozi a first-class resident of your repository.
As far as I know, there has been no other Debian packages for Sozi since version 13.

I have a few questions for you:

- You are using the issue tracker of Sozi. Are you expecting some action from me or is it just an announcement?
- In the copyright notice at [vx-dga-l-sozi-64bits/debian/copyright](https://github.com/Vitalinux-DGA-ProgSoftLibre/vx-dga-l-sozi-64bits/blob/master/debian/copyright), are you supposed to put the license of Sozi itself, or is it the license of the package definition files only?

**Comment by senshu** [comment]
Third question:

- Is there a reason for choosing a different versioning system? Why 1.0-2 instead of the upstream version number 17.02.072116? It may confuse users.

**Comment by senshu** [comment]
My questions were left unanswered for more than one month.
So I will consider that this issue can be closed.

Please join the [sozi-users discussion group](https://groups.google.com/d/forum/sozi-users) for discussions and announcement.
