### ISSUE TITLE
Problem converting Sozi presentations to PDF with 'Sozi 18.01'

### ISSUE THREAD

**Issue by henrythebuilder** [senshu/Sozi#417]
Hi,
I have a problem with Sozi 18.01 converting Sozi presentations to PDF.
With the last version of Sozi the PDF contains only the last frame.
Looking at the output of Sozi 17 and Sozi 18 it seems that the main difference in the html file produced by version 18 is the absence of the 'data-frame-index' parameter.

Steps to reproduce
- Download Sozi 17
- Create the presentation as described on the web site with Sozi 17 with the base document.
- Create the pdf file. 
- Download Sozi 18
- Open the same svg image with Sozi 18 in order to create a new html file
- Create the pdf file

==> First pdf file is ok
==> New pdf file contains only the last frame

Thanks for your work !!!

Note:
- I'm using Sozi on Debian GNU/Linux Installed from a zip archive
- sozi-to-pdf ouput log: [sozi-to-pdf-ouput-with-sozi-18.log](https://github.com/senshu/Sozi/files/1699348/sozi-to-pdf-ouput-with-sozi-18.log), [sozi-to-pdf-ouput-with-sozi-17.log](https://github.com/senshu/Sozi/files/1699349/sozi-to-pdf-ouput-with-sozi-17.log)

**Comment by senshu** [comment]
Conversions to videos and pptx were also affected by this bug.
The problem was related to changes in the code of the Sozi player: sozi-export needed to be updated.
 
This issue is fixed by https://github.com/senshu/Sozi-export/commit/9419e5c555f1fc7c4df2bcbe058498fe72b81357
Sozi-export 18.01 will convert presentations made with Sozi 18.01, 17.11 and earlier.

To upgrade, run `npm update -g sozi-export`

**Comment by henrythebuilder** [comment]
Thanks for the fix :+1:
