### ISSUE TITLE
Allow to create embeddable animations without any frame lists, keyboard shortcuts etc.

### ISSUE THREAD

**Issue by Moini** [senshu/Sozi#454]
### Summary of your problem or feature request

I would like to be able to include the created animation as an 'object', without all the presentation-specific layout. 

I would like to be able to:

- remove the frame list
- remove the keyboard shortcuts

so I can run the whole animation like an animated picture, but without the resolution issues of a video.

### Version of Sozi and other relevant software

* 18.04

### Steps to reproduce the problem

I tried to remove the CSS and the divs with the buttons etc. from the .sozi.html file. Unfortunately, this resulted in the JS having a problem:

`TypeError: u is null`

### Expected behavior

I would like to have a switch in the interface to create an embeddable (as `<object>`) SVG file, with all the necessary JS and all the necessary JSON data inside, and with no presentation controls.

In the short term, I would be happy to get some hints how to workaround this manually. I like the way of working with Sozi, and I like that these are SVG files.

**Comment by senshu** [comment]
> I would like to be able to:
>  *  remove the frame list
>  *  remove the keyboard shortcuts

Maybe I misunderstood your problem. If I remember well, you can already do this in Sozi 18.04. You can disable keyboard and mouse actions in the "Player" section of the right pane.

The field "Allow to control the presentation" can enable or disable all mouse and keyboard actions related to moving from one frame to another, including showing/hiding the frame list.

> I would like to have a switch in the interface to create an embeddable (as `<object>`) SVG file

At the moment, the only supported way to embed a presentation in a web page is [to embed the generated .sozi.html file in an iframe](http://sozi.baierouge.fr/pages/tutorial-embedding.html).
Assuming that you can disable all keyboard shortcuts, what benefits do you expect from embedding an SVG in an `<object>`, rather than embedding an HTML in an `<iframe>`?

**Comment by Moini** [comment]
Thank you, Guillaume, yes, that would work, except that the frame is much too large. The hidden elements seem to still take up space:

![Bildschirmfoto_2019-03-21_01-03-55](https://user-images.githubusercontent.com/3240233/54726893-5290f800-4b75-11e9-9840-f12e8e4f093a.png)
![Bildschirmfoto_2019-03-21_01-02-15](https://user-images.githubusercontent.com/3240233/54726894-5290f800-4b75-11e9-9011-28b26f9a6b19.png)

**Comment by Moini** [comment]
(This is not zoomed in, it's just the first frame in the first pic, and  the end frame in the second )

**Comment by Moini** [comment]
I want to use this as a header image for a website.

**Comment by senshu** [comment]
When you open a Sozi presentation in a browser window or an iframe, the SVG is resized to fill the entire viewport. If you create an iframe with the desired aspect ratio, the embedded presentation should look as expected. The frame list is supposed to be as high as the current window or frame.

If it does not work for you, please send me an example document (SVG + json) that could help me reproduce the problem.

By the way, when the frame list is longer than the height of the iframe, scrollbars can become visible on the left of the SVG. This issue was fixed in the latest development version, available at https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing

**Comment by Moini** [comment]
Thanks to your tip I was able to get rid of the blank spaces above and below the image!

Now the problem is that it doesn't stretch to width. The iframe has the full width, no margins or padding, the html tag in the iframe is full width, and even the SVG tag is full width.

But the SVG content doesn't resize to full width. The original SVG is wider (1920px), so that cannot be the reason.

It's super weird... iframes are ... difficult to handle.

Another [issue with using iframes](https://stackoverflow.com/questions/2648053/preventing-iframe-caching-in-browser
): 

They are cached in Firefox (due to a bug, admittedly, but one that is there for > 7 years already), and the only way around that is to add some js to prevent that - else after the first time playing, you always get the last frame of the animation... super useless.

I had to add 
 ```
<script>
    var _headerframe = document.getElementById("headerframe");
    _headerframe.contentWindow.location.href = _headerframe.src;
    </script>
```

so it can work. 

In Chrome, it loads the SVG before it applies the clips and resizes everything to full height, resulting in a blinking that shows all the offscreen elements in the file, and a miniature version of it, before the animation is played.

I start fearing that I need to try and take the sozi json file and create a CSS animation from it... which would take me days to get it right...

**Comment by senshu** [comment]
I have created a small example to see if I could reproduce your problem:
[sozi-454.tar.gz](https://github.com/senshu/Sozi/files/3025795/sozi-454.tar.gz)

I have followed these guidelines:
* Each frame has an "outline" element (a rectangle) with the desired aspect ratio.
* The iframe has fixed width and height with the same aspect ratio.

> But the SVG content doesn't resize to full width

Sozi can use either the width or height of the container to set its zoom level. It depends on the aspect ratio of the presentation and of the container.
Based on the description of your problem, it is not clear whether you set a specific height for the iframe.

> In Chrome, it loads the SVG before it applies the clips and resizes everything to full height, resulting in a blinking that shows all the offscreen elements in the file

This is fixed in the current development version: on load, the Sozi presentation now shows a black screen and a spinner until all layers are correctly positioned.

**Comment by Moini** [comment]
I didn't set a height, just 100 % width for the container (it needs to be responsive), and I expected it to adjust the height accordingly. Aspect ratio was kept, but it didn't expand to the full width, and although I heavily poked around in the 'Layout' section of the dev tools of the browser, I wasn't able to find out why that was happening.

Ah, that's good about the fix for Chrome!

So, what I have done now was that I used the animation created in Sozi as a draft, for creating one with CSS animations (+SMIL for animated gradients) that copies it. I still haven't got all the movements correctly (it's much, much easier to do that with Sozi, as it allows to effortlessly combine movements). 

However, I was able to embed the SVG as an object into the page, and width/height adjustment just works now. There's still some work in it due to zooming centers and translations not being balanced perfectly yet (I'm not into 3D translations, maybe I should have tried those...).

It had worked with the old Inkscape extension sozi, for my other website: https://vektorrascheln.de, where I used an 'embed' tag.

I love Sozi, but I guess it's better suited for its actual purpose of creating presentations. Thank you for having taken the time to try and help me, Guillaume!
